import Image from "next/image";
import Link from "next/link";
import Reveal from "@/components/Reveal";
import ServiceCarousel, { HomeService } from "@/components/ServiceCarousel";

export const metadata={title:"Hospitality Staffing & Cleaning Dubai | Durrat Al Noor",description:"Hospitality staffing, housekeeping, food and beverage, kitchen support, pool and leisure staffing, and deep cleaning services in Dubai and across the UAE."};

const services:HomeService[]=[
{title:"Housekeeping Services",description:"Reliable housekeeping and cleaning support for hospitality and property environments.",bullets:["Room attendants","Public-area teams","Supervisory support","Residential & office cleaning","Schools & government facilities"],image:"https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",alt:"Professional hotel housekeeping service"},
{title:"Food & Beverage Staffing",description:"F&B personnel to support restaurants, hotels, banquets and events around your operation.",bullets:["Waiters & waitresses","Restaurant service","Banquet staff","Bar support","Event personnel"],image:"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80",alt:"Restaurant food and beverage service"},
{title:"Kitchen & Stewarding",description:"Kitchen support personnel for food preparation, stewarding and smooth daily operations.",bullets:["Kitchen stewards","Commis chefs","Culinary support"],image:"https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1200&q=80",alt:"Professional commercial kitchen"},
{title:"Pool & Leisure Services",description:"Pool and recreation personnel for hospitality and leisure environments with agreed schedules.",bullets:["Pool lifeguards","Beach lifeguards","Recreation attendants"],image:"https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1200&q=80",alt:"Luxury resort pool and leisure area"},
{title:"Deep Cleaning Services",description:"Deep cleaning arranged around your property's scope, tasks, materials, equipment and schedule.",bullets:["Commercial buildings","Residential properties","Villas","Restaurants"],image:"https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80",alt:"Professional deep cleaning service"}
];

export default function Home(){return <div>
<section className="relative flex min-h-[100dvh] min-h-screen w-full items-center justify-center overflow-hidden bg-[#0B192C] pb-12 pt-28 text-white md:pt-36">
<div className="absolute inset-0 z-0 h-full w-full bg-[url(/images/hero-fallback.jpg)] bg-cover bg-center"/>
<video autoPlay muted loop playsInline preload="metadata" poster="/images/hero-fallback.jpg" aria-label="Durrat Al Noor Hospitality background video" className="absolute inset-0 z-0 h-full w-full object-cover"><source src="/bg-video-2.mp4" type="video/mp4"/></video>
<div className="hero-overlay absolute inset-0 z-10 h-full w-full"/>
<div className="container relative z-20 flex w-full flex-col justify-center"><div className="max-w-4xl">
<p className="eyebrow">People. Service. Excellence.</p><h1 className="mt-5 hero-title">Hospitality Staffing &amp; Cleaning Services in Dubai</h1>
<div className="mt-9 flex flex-wrap gap-4"><Link href="/our-services/" className="gold-button rounded-full px-7 py-4 font-bold">Explore Our Services</Link><Link href="/contact-us/" className="gold-button rounded-full px-7 py-4 font-bold">Contact Us</Link></div>
</div></div></section>

<section className="section"><Reveal><div className="container"><div className="mb-12 max-w-4xl"><p className="eyebrow">Hospitality Support Built Around Your Operation</p><h2 className="heading mt-3">Service shaped around your property.</h2><p className="copy mt-5 text-lg">Thoughtful service starts with the right people.</p><p className="copy mt-4">Durrat Al Noor Hospitality provides housekeeping, food and beverage staffing, kitchen and stewarding support, pool and leisure personnel, and deep cleaning services in Dubai and across the UAE. From daily operations to temporary staffing requirements, we help hotels, restaurants, businesses and residential clients find support suited to their needs.</p></div><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="copy mt-5">Every property has its own service standards, schedules and priorities. We take time to understand yours.</p><p className="copy mt-4">Whether you need housekeeping personnel, restaurant service staff or deep cleaning for your building, our team works with you to define the required roles, scope and service arrangements.</p><p className="copy mt-4">Based in Al Karama, Dubai, Durrat Al Noor Hospitality brings people and operational support together with a focus on clear communication, professional conduct and care.</p><Link href="/about-us/" className="mt-7 inline-block font-bold underline decoration-[#DAB672] decoration-2 underline-offset-8">Learn More About Us →</Link></div>
<div className="relative h-[420px] w-full overflow-hidden rounded-[32px] hover-image"><Image src="https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1400&q=80" alt="Hospitality property in Dubai" fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/></div></div></div></Reveal></section>

<section className="section bg-white"><Reveal><div className="container"><p className="eyebrow">Our Hospitality &amp; Cleaning Services</p><h2 className="heading mt-3 max-w-4xl">Practical support for people, properties and daily operations.</h2><ServiceCarousel services={services}/><div className="mt-10 flex w-full justify-center"><Link href="/our-services/" className="inline-block rounded-full border border-[#DAB672] px-7 py-3.5 font-bold hover:bg-[#DAB672]/10">Explore All Five Services →</Link></div></div></Reveal></section>

<section className="section"><Reveal><div className="container grid gap-6 lg:grid-cols-2"><div className="card p-8 md:p-10"><p className="eyebrow">Flexible Staffing Arrangements</p><h2 className="heading mt-3 text-3xl">Support that fits your schedule.</h2><p className="copy mt-4">We offer casual staffing, full-time employment support and internship programmes for applicable roles. Tell us the personnel you need, the intended duration and your preferred schedule so we can discuss a suitable arrangement.</p></div><div className="rounded-[24px] bg-[#0B192C] p-8 text-white md:p-10"><p className="eyebrow">A Clear Approach to Service</p><ol className="mt-6 grid gap-6">{[["1. Understand your needs","We discuss your property, service priorities, staffing requirements and schedule."],["2. Agree the details","The scope, personnel, availability and pricing are confirmed before service begins."],["3. Coordinate the work","Our team stays in contact to support the agreed arrangements and discuss changing requirements."]].map(([t,d])=><li key={t}><h3 className="font-bold">{t}</h3><p className="mt-1 text-sm leading-7 text-white/90">{d}</p></li>)}</ol></div></div></Reveal></section>

<section className="section bg-white text-[#122136]"><Reveal><div className="container flex flex-col justify-between gap-7 md:flex-row md:items-center"><div><p className="eyebrow">Looking for Hospitality or Cleaning Support?</p><h2 className="mt-3 text-3xl font-black">Tell us what you need and where you need it.</h2><p className="mt-3 max-w-2xl text-[#405066]">We will review your enquiry and discuss the next steps.</p></div><div className="flex flex-wrap gap-3"><Link href="/contact-us/" className="gold-button rounded-full px-7 py-4 font-bold">Discuss Your Requirements</Link><a href="https://wa.me/971582774427" className="rounded-full border border-[#122136]/20 px-7 py-4 font-bold text-[#122136] hover:border-[#DAB672]">WhatsApp Us</a></div></div></Reveal></section>
</div>}